set_property PACKAGE_PIN T8 [get_ports {decoded[0]}]
set_property PACKAGE_PIN V9 [get_ports {decoded[1]}]
set_property PACKAGE_PIN R8 [get_ports {decoded[2]}]
set_property PACKAGE_PIN T6 [get_ports {decoded[3]}]
set_property PACKAGE_PIN U9 [get_ports {received[0]}]
set_property PACKAGE_PIN U8 [get_ports {received[1]}]
set_property PACKAGE_PIN R7 [get_ports {received[2]}]
set_property PACKAGE_PIN R6 [get_ports {received[3]}]
set_property PACKAGE_PIN R5 [get_ports {received[4]}]
set_property PACKAGE_PIN V7 [get_ports {received[5]}]
set_property PACKAGE_PIN V6 [get_ports {received[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {decoded[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {decoded[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {decoded[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {decoded[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {received[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {received[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {received[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {received[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {received[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {received[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {received[0]}]
set_property PACKAGE_PIN L16 [get_ports valid]
set_property PACKAGE_PIN P4 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports valid]

## Clock signal
##Bank = 35, Pin name = IO_L12P_T1_MRCC_35,					Sch name = CLK100MHZ
set_property PACKAGE_PIN E3 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports clk]

set_property IOSTANDARD LVCMOS33 [get_ports {syndro[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {syndro[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {syndro[0]}]
set_property PACKAGE_PIN P2 [get_ports {syndro[2]}]
set_property PACKAGE_PIN R2 [get_ports {syndro[1]}]
set_property PACKAGE_PIN U1 [get_ports {syndro[0]}]
